name: Setup
description: Setup the repository

inputs:
  cache-version:
    description: A string to forcefully bust the cache when changed
    required: false
    default: v1
  deno-deps-cache-slice-name:
    description: A string to differentiate the Deno dependencies slice from other slices of the cache. This is needed only if there are other slices that shouldn't be confused with this slice.
    required: false

runs:
  using: composite
  steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      env:
        DENO_CACHE_SLICE_NAME: deno
      with:
        deno-version: 2.x
        cache: true
        cache-hash: ${{ runner.os }}-${{ env.DENO_CACHE_SLICE_NAME }}@${{ inputs.cache-version }}

    - name: Set up Deno dependencies cache
      uses: actions/cache@v3
      env:
        # Don't add more paths below, since they'll be invalidated whenever Deno deps change
        # Yoinked from https://github.com/actions/cache/blob/main/examples.md#linux
        DENO_DEPS_CACHE_PATH: |
          ~/.deno
          ~/.cache/deno
      with:
        path: ${{ env.DENO_DEPS_CACHE_PATH }}
        key: ${{ runner.os }}-${{ inputs.deno-deps-cache-slice-name }}@${{ inputs.cache-version }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.deno-deps-cache-slice-name }}@${{ inputs.cache-version }}

    - name: Install dependencies
      run: deno install
      shell: bash
