name: CI

on: [push, pull_request]

env:
  # Used to differentiate from other slices of the cache for other workflow runs, and to forcefully bust the cache when renamed
  CACHE_KEY_BASE: ci@v1

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
          cache-hash: ${{ env.CACHE_KEY_BASE }}-${{ hashFiles('deno.lock') }}

      - name: Install dependencies
        run: deno install

  test:
    name: Test
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Now the Deno cache should be warmed up, so this should be much faster
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
          cache-hash: ${{ env.CACHE_KEY_BASE }}-${{ hashFiles('deno.lock') }}

      - name: Test
        run: deno test --allow-read
