name: CI

on: [push, pull_request]

env:
  # Used to forcefully bust the cache
  CACHE_VERSION: v1
  # Used to differentiate from other slices of the cache for other workflow runs
  CACHE_SLICE_NAME: ci

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Repository
        uses: ./.github/actions/fn-setup
        with:
          cache-version: ${{ env.CACHE_VERSION }}
          deno-deps-cache-slice-name: ${{ env.CACHE_SLICE_NAME }}

  test:
    name: Test
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Now the Deno cache should be warmed up, so this should be much faster
      - name: Set up Repository
        uses: ./.github/actions/fn-setup
        with:
          cache-version: ${{ env.CACHE_VERSION }}
          deno-deps-cache-slice-name: ${{ env.CACHE_SLICE_NAME }}

      - name: Test
        run: deno test --allow-read
