name: Deno CI (test run)

on:
  push:
    branches:
      - infra/actions/denoize

env:
  # Used to differentiate from other slices of the cache for other workflow runs, and to forcefully bust the cache when renamed
  CACHE_KEY_BASE: deno-ci@v1

jobs:
  deno-job:
    name: Run Deno test run job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
          cache-hash: ${{ env.CACHE_KEY_BASE }}-${{ hashFiles('deno.lock') }}

      - name: Install dependencies
        run: deno install

      - name: Run test run script
        run: deno run --allow-env @encode/ci
